#!/bin/sh
#
# Regression test: the size-scaled replay deadline has a ceiling.
#
# The master bounds a whole scrollback replay by
#
#     started + CLIENT_REPLAY_TIMEOUT + bytes / CLIENT_REPLAY_MIN_RATE
#
# The scaled term keeps a healthy client on a slow link from being dropped
# just for having a large scrollback. But main.c accepts any -b size with no
# upper bound, so without a ceiling the scaled term grows without limit: a
# session started with -b 1024m would give a replay 16384 seconds of grace,
# and one client trickling just above the minimum rate would hold the master,
# the pty child (blocked on write once the pty buffer fills) and every other
# attached client for over four hours.
#
# This is arithmetic, so it is tested as arithmetic: the deadline code is
# lifted verbatim out of master.c, compiled against a stub scrollback, and
# asked what deadline it hands out for a range of buffer sizes. That keeps
# the test honest (it runs the shipped code, not a copy of it) and fast
# (seconds, rather than the hours the uncapped bound would take to observe).
#
# Checks:
#   1. the deadline still scales for sizes within the supported range
#   2. an outsized scrollback is clamped to the ceiling
#   3. no scrollback size, however absurd, can push the deadline past a
#      hard sanity bound
#
# Usage: tests/replay_deadline_cap.sh [path-to-dtach]
# Exit status: 0 = PASS, 1 = FAIL.

set -u

HERE=$(cd "$(dirname "$0")" && pwd)
SRCDIR=$(cd "$HERE/.." && pwd)
SRC=$SRCDIR/master.c

# The deadline may never exceed this many seconds, whatever -b was. It is
# deliberately not derived from the source: a build that raises its own
# ceiling to something absurd must fail this test, not redefine it.
SANITY_MAX=900

WORK=/tmp/dtachtest-cap-$$.d
rm -rf "$WORK"
mkdir -p "$WORK"

rc=0
note_fail() {
	echo "   FAIL: $1"
	rc=1
}
note_pass() {
	echo "   PASS: $1"
}

cleanup() {
	rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

if [ ! -f "$SRC" ]; then
	echo "FAIL: no master.c at $SRC"
	exit 1
fi

##############################################################################
# Lift the deadline code out of master.c, verbatim.
##############################################################################
DEFINES=$(grep '^#define CLIENT_REPLAY' "$SRC")
if [ -z "$DEFINES" ]; then
	echo "FAIL: no CLIENT_REPLAY_* constants in master.c"
	exit 1
fi

fn_start=$(grep -n '^scrollback_replay_bytes(void)$' "$SRC" | head -1 |
	cut -d: -f1)
fn_named=$(grep -n '^client_replay_deadline(time_t started)$' "$SRC" |
	head -1 | cut -d: -f1)
if [ -z "${fn_start:-}" ] || [ -z "${fn_named:-}" ]; then
	echo "FAIL: could not find the deadline functions in master.c"
	exit 1
fi
fn_start=$((fn_start - 1))
fn_end=$(awk -v s="$fn_named" 'NR > s && /^}$/ { print NR; exit }' "$SRC")
if [ -z "${fn_end:-}" ]; then
	echo "FAIL: could not find the end of client_replay_deadline()"
	exit 1
fi
FUNCS=$(sed -n "${fn_start},${fn_end}p" "$SRC")
echo "lifted master.c lines ${fn_start}-${fn_end} plus the CLIENT_REPLAY_* defines"

cat > "$WORK/harness.c" <<EOF
/* Generated by tests/replay_deadline_cap.sh. The two functions and the
** constants below are copied out of master.c unchanged. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <time.h>

/* Stub of the master's scrollback buffer: the fields the lifted code reads. */
static struct {
	unsigned char *data;
	size_t size;
	size_t used;
	size_t head;
} scrollback;

$DEFINES

$FUNCS

int main(int argc, char **argv)
{
	static unsigned char byte;

	if (argc != 2)
		return 2;
	if (strcmp(argv[1], "consts") == 0)
	{
		printf("%ld %ld ", (long)CLIENT_REPLAY_TIMEOUT,
		       (long)CLIENT_REPLAY_MIN_RATE);
#ifdef CLIENT_REPLAY_MAX_SCALED
		printf("%ld\n", (long)CLIENT_REPLAY_MAX_SCALED);
#else
		printf("none\n");
#endif
		return 0;
	}
	scrollback.data = &byte;
	scrollback.used = (size_t)strtoull(argv[1], NULL, 10);
	scrollback.size = scrollback.used;
	scrollback.head = 0;
	printf("%ld\n", (long)client_replay_deadline((time_t)0));
	return 0;
}
EOF

CC=${CC:-cc}
if ! $CC -o "$WORK/harness" "$WORK/harness.c" > "$WORK/cc.log" 2>&1; then
	echo "FAIL: could not compile the lifted deadline code"
	cat "$WORK/cc.log"
	exit 1
fi

consts=$("$WORK/harness" consts)
TOTAL=$(echo "$consts" | awk '{print $1}')
MIN_RATE=$(echo "$consts" | awk '{print $2}')
MAX_SCALED=$(echo "$consts" | awk '{print $3}')
echo "grace ${TOTAL}s, minimum rate ${MIN_RATE}B/s, scaled-term ceiling ${MAX_SCALED}"

if [ "$MAX_SCALED" = "none" ]; then
	note_fail "master.c defines no ceiling on the scaled term, so -b"
	note_fail "decides how long one client may hold the session"
	echo "== result =="
	echo "FAIL: see the failures above"
	exit 1
fi

deadline() {
	"$WORK/harness" "$1"
}

##############################################################################
# 1. Sizes inside the supported range keep their full scaled deadline.
##############################################################################
echo "== scaling below the ceiling is untouched =="
for mb in 1 4 16; do
	bytes=$((mb * 1024 * 1024))
	scaled=$((bytes / MIN_RATE))
	[ "$scaled" -le "$MAX_SCALED" ] || continue
	want=$((TOTAL + scaled))
	got=$(deadline "$bytes")
	if [ "$got" = "$want" ]; then
		note_pass "${mb}MB scrollback gets ${got}s (grace plus ${scaled}s of data)"
	else
		note_fail "${mb}MB scrollback got ${got}s, expected ${want}s"
	fi
done

##############################################################################
# 2. An outsized scrollback is clamped.
##############################################################################
echo "== an outsized -b is clamped =="
GB=$((1024 * 1024 * 1024))
want=$((TOTAL + MAX_SCALED))
uncapped=$((TOTAL + GB / MIN_RATE))
got=$(deadline "$GB")
if [ "$got" = "$want" ]; then
	note_pass "1GB scrollback gets ${got}s, not the unclamped ${uncapped}s"
else
	note_fail "1GB scrollback got ${got}s, expected the ${want}s ceiling"
	note_fail "(unclamped this size would be ${uncapped}s)"
fi

##############################################################################
# 3. No size at all can push the deadline past the sanity bound.
##############################################################################
echo "== no size passes the ${SANITY_MAX}s sanity bound =="
for bytes in 1073741824 68719476736 1099511627776; do
	got=$(deadline "$bytes")
	if [ "$got" -le "$SANITY_MAX" ] && [ "$got" -ge "$TOTAL" ]; then
		note_pass "$bytes bytes gives ${got}s"
	else
		note_fail "$bytes bytes gives ${got}s, outside [${TOTAL}, ${SANITY_MAX}]"
	fi
done

##############################################################################
echo "== result =="
if [ "$rc" -eq 0 ]; then
	echo "PASS: the scaled deadline scales inside the supported range and"
	echo "      is clamped above it, so -b cannot decide how long one"
	echo "      client holds the session"
else
	echo "FAIL: see the failures above"
fi

exit $rc
